### PR TITLE
Represent app.d as module

### PR DESCRIPTION
**Pull request by denizzzka**
It is useful for external usage of grabbing code

### CODE REVIEW

**Comment by WebFreak001** [comment]
uh this comes with plenty of issues with dub, app.d is generally ignored, it is not unittestable and the file name doesn't match the module name which can create problems with tools. Plus the main function in there will mess up with programs trying to access this as a library and it is doing seemingly random file reads and using a global variable for reading settings which also does not make it thread safe. I think the functions would need to be refactored to take in arguments properly and add documentation instead of just making this a module.

**Comment by denizzzka** [comment]
Well, at least for now?

The fact is that I want to make a similar bot for the telegram, but there is another specificity of working with its notification channels and it will be problematic to make it within your code.

**Comment by WebFreak001** [comment]
hm no that's not a good idea. If you want to make something like that though, feel free to fork it and work on your project without submitting any PR, that's a very easy and good way to do what you want to do. If you do, you should definitely do so in a separate branch to be able to get in changes more easily.

Though I don't think I can merge this PR, making the functions available as a module takes a little bit more thought and some of the functions would need to be rewritten more.

**Comment by denizzzka** [comment]
Why duplicate code that parses sites?

**Comment by WebFreak001** [comment]
move the code and make app.d depend on it itself, not duplicate it. Then it is also easier extensible and easier to use in other projects.

**Pull request closed without merging**
